In [4]:
#You declare the variable without type.
a= 3
b= True
c='String'
print(a,b,c)

3 True String


In [5]:
print(5/2)
print(int(5/2))


2.5
2


In [13]:
#Loops
arr = [1,2,3,4,5]
print('show array with for in')
for x in arr:
    print(x)
print('show array with for in range')
#print(len(arr))
for x in range(len(arr)):
    print(x)
print('show even numbers')
for x in arr:
    if x%2 == 0:
        print(x)


for in
1
2
3
4
5
for in range
1
2
3
4
5
even numbers
2
4


In [36]:
# Array Indexing:
# arr = [0,1,2,3,4,5]
# print(arr[0:3])

# import numpy as np


# origMat = np.array(arr)
# mat = np.copy(origMat)
# print(mat)
# mat[0:3] = 0
# print(mat)
# mat = np.copy(origMat)
# mat[(mat%2==0)]=-1
# print(mat)

Arr = np.zeros(shape=(5,5,5),dtype=np.uint8)
Arr[0:3,0:4,1] = 20

print(Arr)

[[[ 0 20  0  0  0]
  [ 0 20  0  0  0]
  [ 0 20  0  0  0]
  [ 0 20  0  0  0]
  [ 0  0  0  0  0]]

 [[ 0 20  0  0  0]
  [ 0 20  0  0  0]
  [ 0 20  0  0  0]
  [ 0 20  0  0  0]
  [ 0  0  0  0  0]]

 [[ 0 20  0  0  0]
  [ 0 20  0  0  0]
  [ 0 20  0  0  0]
  [ 0 20  0  0  0]
  [ 0  0  0  0  0]]

 [[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]

 [[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]]


In [31]:
origMat = np.array([
                   [1,2,3,4,5],
                   [1,2,3,4,5],
                   [1,2,3,4,5]
                   ])
mat = np.copy(origMat)
print(mat)
mat[1:3,1:3] = 0
print(mat)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 0 0 4 5]
 [1 0 0 4 5]]


In [30]:
arrZeros=np.zeros((6,5))
arrOnes=np.ones((6,5))
print(arrZeros)
print(arrOnes)
print(arrOnes.shape)
print(arrOnes.shape[0])

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(6, 5)
6


In [26]:
# Shows the fact that Python uses KEYWORD ARGUMENTS as well as the traditional positional arguments.
## Notice that: in the output of the first and second call to function fun are the same.
## In the second call (using keywords arguments), sorting arguments is not needed.


def fun(x,y,z):
    print (x,y,z)
    
fun(1,2,3);
fun(z=3,y=2,x=1)

1 2 3
1 2 3


In [23]:
#instead of NULL: None

x = None
if (x==None):
    print('x is None')


None
